build: false
skip_branch_with_pr: true

environment:
  PYTHON: "C:\\Python37"

  CONAN_REFERENCE: "libp2p/0.1"
  CONAN_USERNAME: "matt1795"
  CONAN_UPLOAD: "https://api.bintray.com/conan/matt1795/public-conan"
  REMOTE_NAME: "remote"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 12
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan remote add %REMOTE_NAME% %CONAN_UPLOAD%
  - conan user
  - conan --version

build_script:
  - conan create . %CONAN_USERNAME%/testing
